server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
#            - After -> ?? ?? ??
#            - Before -> ?? ?? ??
#            - Between -> ?? ?? ??
#            - Cooke -> name, regExp
#            - Method=GET -> method
          filters:
            - AddRequestHeader=token, 123456 #name: value
            - AddResponseHeader=authenticated, yes
            - RewritePath=/user/?(?<segment>.*), /$\{segment}
#   rewritePath -> prefix????? ????? ??? ?
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
